language: java
jdk:
- oraclejdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle
env:
  global:
    secure: QdDUgWDAbhA8lxSd69S5LeFc0nCvjH5BCdhwy6K0AWpqZZ/ida5V1iFYvKPtjsY0xle+hMGrVbV+wj8bJe2gIg3gQEN0av9XyGrWKE2BqA6TAgityAnbbseHA+v4cnRHpf16Sj7Dj4E1LepuEkEpyGR+sJOEtNEmi4dMlmO3Pu4mY0boi9cHCFT5SrcB/cfxnPycQ34k9sk22ayszc24DuvZjnpFn0xZoQ/gt5jslem+JjweZczV2fSkJRJAdrrbresZ/PfwpS2g1GQP5IShRWWcTNQkaWf6sU+6SJ2z9HSGRwNfhmJbpuoR6I/ImtdM5dU1LM/MVRjHRsZTBAYvUnoqTGL54CvkWYrttCyrZly1lrO6rBNfmDFtzqsalZZTdtm01pI2Va9iXg1Xi/QiLFJO21xsGg0jjRqe3FsKOq0Ge35idy9THCTvYkcpT8eA3qTIDr/SpOH128gcIfgwBUZAct2VNeWf9XdzpQg91YPB9XRORw3gY2NcJ7C7KdWzWXlIOREf610jmFoBD8OV9VOGXNDP7wzmFg5aAXUzLKjEUhfYKN7ssSmP22C5ujDTclG8FR8iNHk6CJnu7MpkRETET0nwjOZCtoh6KnfeWBVWyAN5vGNOufJRnAdxjLVCHCXEIyxVIG47YURHB890HsJjk8zvwC/BYHEFiB9zDQ0=
    secure: Hu1lb6xWesPwEHn75REPjplVle9VrYgRP4wPUjVeZw2b4PVfxjTFeRZRH3jjWRsXxFSYjqojz8NB+kGmEobwFwVBnyP4argnkPWPVAM6GDlynQ6sDlsJeP5tleHb1MSI0cFp7j3PhV6K0PiR+Os7m6RtYTDTFSKsU6DzzkLi6PIn4kdXib/FAJnv7Ezvi9WM1oC0CnsSklKhCiZwq+4qVW0p6LhP3X42LQ/1mvJNXeBXfPKkCsIZBHrxxFw1p94as+Rx4TYFxMibdea2TOuFXW8yGamJMRkUpOrBBp1eZ2ZSVf/hlxJ97E0PiY+KH/Q1FenS+6dMm0Wp6n9t7TCUUe1NzcpH+d2NjkaZTzvI0XWmPPyQlW5lc+5iGbxecv/qkwQwhCHgWcFR9+hv7kvwGTCweAmBXaHdIDLp7PSRz8I6YfQOujHcH8nDC0xWayXS3fbZG+c55AFBoyS+1TL/Cx6nzYRnYFOAyItLvD0EkkgGYCWrBTU2rQr4jAiK1crPcvi2GAJ+QluCOlO7mh7V7jPOq4lsXAU3PkwGsIe/baUnyBxfGm3cV0KaRMAkO8+hwRMs7ZAyPyOXkWwLe0VK1wuuT7vzzTEwE7/xnv+RJv1DKwECBkN2uBi1Ycf+iJyINcBoQWfoNAM81CSTQBBu7K87y1vCqvz3h9NQPZO24es=
