language: java
jdk:
- oraclejdk8
sudo: false
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
cache:
  directories:
  - $HOME/.gradle
env:
  global:
  - secure: Hu1lb6xWesPwEHn75REPjplVle9VrYgRP4wPUjVeZw2b4PVfxjTFeRZRH3jjWRsXxFSYjqojz8NB+kGmEobwFwVBnyP4argnkPWPVAM6GDlynQ6sDlsJeP5tleHb1MSI0cFp7j3PhV6K0PiR+Os7m6RtYTDTFSKsU6DzzkLi6PIn4kdXib/FAJnv7Ezvi9WM1oC0CnsSklKhCiZwq+4qVW0p6LhP3X42LQ/1mvJNXeBXfPKkCsIZBHrxxFw1p94as+Rx4TYFxMibdea2TOuFXW8yGamJMRkUpOrBBp1eZ2ZSVf/hlxJ97E0PiY+KH/Q1FenS+6dMm0Wp6n9t7TCUUe1NzcpH+d2NjkaZTzvI0XWmPPyQlW5lc+5iGbxecv/qkwQwhCHgWcFR9+hv7kvwGTCweAmBXaHdIDLp7PSRz8I6YfQOujHcH8nDC0xWayXS3fbZG+c55AFBoyS+1TL/Cx6nzYRnYFOAyItLvD0EkkgGYCWrBTU2rQr4jAiK1crPcvi2GAJ+QluCOlO7mh7V7jPOq4lsXAU3PkwGsIe/baUnyBxfGm3cV0KaRMAkO8+hwRMs7ZAyPyOXkWwLe0VK1wuuT7vzzTEwE7/xnv+RJv1DKwECBkN2uBi1Ycf+iJyINcBoQWfoNAM81CSTQBBu7K87y1vCqvz3h9NQPZO24es=
  - secure: Phd2+gV2OYlgo7z05Y6j2L9QFMIzKnVJvgojA7H2oZnwNBsON6GusqnYQjnG3ZQaTvfSp/BmFXNgGbm+ggAQTkgY4V4kdDsFbAKWmPAZkekqg+gNdpSsEKRDgz2NoMKDD7LZRKpSNUkPVGPqYXAkiuOgKRfS6ZsVN7jWu/NWjOu0KOKwaOul2Mb2xL0kp3/YOQzVm5VSb4aD656XSvydumHi1Phgrik8uMG1fKPP9x/Td4ULQINeLi/QW9tybBBmx3UuSqF/QJyzSJCRz8HV+P8jjQ3HFstmRWzlxX7wmejl5Aj5XgbumdQ2JHmLZr3J3M5Bk56SuSFHDCiILdEqQcbl5EFEfJz1lWLYsBMlpX1BZFfRKW34HwPnuclc3QiuXmola4Jr7vXmFXUXxCfYaARKWv1lg9LehiysUBwEYy64ubrRffxLIpkqxHYUps/yYW/GkJnhEbY81asLoO7yHvW5NiAhRzNousol+zpFe5+dyTB7g6ybYIPosgUKR9mknvgd+qy/idrRTijtJGomnTYKu3oW5UdXOq5JiRsxJ9xeks6VbMm1La4uuR6DKUyTsx1FrKD30VhfaDo0tOMMRw24BzaNpzDZR2IMLf30YGuuxI6IEmilZlBAH+vnOxdF5HuPTRI6wdu7oPR391slu9+YY6L6yClqLOMyymoUxC8=
